---
title: "HW4_Format_Word_Test"
author: "Yuan Yi Chen (Eve)"
date: "2017年6月7日"
output: html_document
---
###**A. Introduction**

####This data is provided a Portuguese banking institution which conducted a marketing campaigns to promote their product. Our goal is to predict if the client will subscribe a term deposit (variable y). We will run several models including neural network, random search (GBM), ensemble, random forest, GBM and logistic regression models. We hope to know:
  * The trade off between training time and accuracy.
  * Will feature selection increases the accuracy?


####The general steps are
  * Manipulate our data set (data wrangling & graphs)
  * Apply different models to the clean data set (with all features)
  * Make prediction and view the accuracy and ROC curve
  * Do feature selection (variable importance)
  * Rebuild models based on limited features
  * Make prediction, AUC and ROC curve (with limited features)

####In order to let readers view the explicit results, I would only include 6 models in this report. That is, regarding to neural network models, only the model with highest AUC will be included in this report. Please refer to the other file __ if you want to view the whole results of totally 26 models.

***

###**B. Brief Summarization** 

#####From the following table, We can clearly see that all the AUCs of models fall between 0.9 and 0.94. This means after we train and validate our data set, the prediction of whether consumers will subscribe a product has a high AUC between 0.9 and 0.94.


Models | AUC | Processing time (Sec)        
----|---------|-----------------------------------------------
**Neural Network (the best model within all NN models)**| 0.9246779 | 467.39
**Random Search (with GBM algorithm)**| 0.9272052  |86.29
**Ensemble (random forest + GBM + NN)**| 0.9317667 | 4.05
**GBM**| 0.9272052 | 86.29
**Random Forest**| 0.931621 | 160.78
**Logistic Regression**| 0.9049404 | 2.78

#####In a tradeoff perspective, we can further think about the tradeoff between accuracy(AUC) and the processing time. For example, although the logistic regression has the smallest processing time, its accuracy falls behind other models. Generally speaking, it's not a bad model because perhaps 2~3% AUC difference may not have great impact to our prediction. However, If it's the bioinformatic data, then it's worth to spend lots of time and CPU/GPC to get the model because even 0.01% increases of AUC can benefit the society.


#####In sum, it seems to me that I would choose the logistic model because of its short processing time. In the marketing world, timing and the feedback from our customers are the most important things. As an analyst in this bank who co-works with the marketing team, I am more prone to send the results to the marketing team for them to modify their marketing strategy.

#####On the other hand, if this bank pursues the accuracy (AUC), I may use random forest model instead. It's because although the ensemble model increase the AUC for around 0.001, random forest has the shortest processing time. Furthermore, if we have enough computational resources, we can increase the amount of trees to have higher accuracy. This may not cause the overfitting.
