---
title: "HW4_Format_Word_Test"
author: "Yuan Yi Chen (Eve)"
date: "2017年6月7日"
output: html_document
---
```{r, include=FALSE}
###1. Setup
#Remove Objects
rm(list=ls())

#Clear Memory
gc(reset=TRUE)

#Set Working Directory
setwd("C:/Users/Eve/Dropbox/UCLA Files/Courses/418 Tools of Data Science/STATS 418 - HW4")

#Load packages
library(readr)
library(ROCR)
library(ggplot2)
library(dplyr)
```
```{r, include = F}
#Original data set
data <- read.csv("test.csv")
#Subscription data set (consumers did subscribe the product)
subscribe <- data[which(data$y == "Y"),]
```


```{r, include=FALSE}
#####Job vs subscription
data_job = subscribe %>%
  group_by(job) %>%
  summarise(n = n())
```
```{r, echo = FALSE}
ggplot(data=data_job, aes(x=job, y=n))+
  geom_bar(stat = "identity", aes(fill = job))+ 
  theme_bw()+ coord_flip() + 
  xlab("Different Types of Jobs") + ylab("Numbers of Subscriptions") + ggtitle("Job v.s. Subscription")
```

```{r, include=FALSE}
#####marital vs subscription
data_marital = subscribe %>%
  group_by(marital) %>%
  summarise(n = n())
```
```{r, echo = FALSE}
#marital v.s. Subscription
ggplot(data=data_marital, aes(x=marital, y=n))+
  geom_bar(stat = "identity", aes(fill = marital))+ 
  theme_bw()+ coord_flip() + 
  xlab("Different Marital Status") + ylab("Numbers of Subscriptions") + ggtitle("Marital v.s. Subscription")
```


```{r, include=FALSE}
#####education vs subscription
data_education = subscribe %>%
  group_by(education) %>%
  summarise(n = n())
```
```{r, echo = FALSE}
#education v.s. Subscription
ggplot(data=data_education, aes(x=education, y=n))+
  geom_bar(stat = "identity", aes(fill = education))+ 
  theme_bw()+ coord_flip() + 
  xlab("Different Education Background") + ylab("Numbers of Subscriptions") + ggtitle("Education v.s. Subscription")
```

```{r, include=FALSE}
#####balance vs subscription
data_balance = subscribe %>%
  group_by(balance) %>%
  summarise(n = n())
```
```{r, echo = FALSE}
#balance v.s. Subscription
ggplot(data=data_balance, aes(x=balance, y=n))+
  geom_bar(stat = "identity", aes(fill = balance))+ 
  theme_bw()+ coord_flip() + 
  xlab("Different balance") + ylab("Numbers of Subscriptions") + ggtitle("Balance v.s. Subscription")
```


```{r, include=FALSE}
#####age vs subscription
data_age = subscribe %>%
  group_by(age) %>%
  summarise(n = n())
```
```{r, echo = FALSE}
#age v.s. Subscription
ggplot(data=data_age, aes(x=age, y=n))+
  geom_bar(stat = "identity", aes(fill = age))+ 
  theme_bw()+ coord_flip() + 
  xlab("Different age") + ylab("Numbers of Subscriptions") + ggtitle("Age v.s. Subscription")
```

```{r, include=FALSE}
#####housing vs subscription
data_housing = subscribe %>%
  group_by(housing) %>%
  summarise(n = n())
```
```{r, echo = FALSE}
#housing v.s. Subscription
ggplot(data=data_housing, aes(x=housing, y=n))+
  geom_bar(stat = "identity", aes(fill = housing))+ 
  theme_bw()+ coord_flip() + 
  xlab("Housing") + ylab("Numbers of Subscriptions") + ggtitle("Housing v.s. Subscription")
```


```{r, include=FALSE}
#####loan vs subscription
data_loan = subscribe %>%
  group_by(loan) %>%
  summarise(n = n())
```
```{r, echo = FALSE}
#balance v.s. Subscription
ggplot(data=data_loan, aes(x=loan, y=n))+
  geom_bar(stat = "identity", aes(fill = loan))+ 
  theme_bw()+ coord_flip() + 
  xlab("Loan") + ylab("Numbers of Subscriptions") + ggtitle("Loan v.s. Subscription")
```



```{r, include=FALSE}
#####contact vs subscription
data_contact = subscribe %>%
  group_by(contact) %>%
  summarise(n = n())
```
```{r, echo = FALSE}
#contact v.s. Subscription
ggplot(data=data_contact, aes(x=contact, y=n))+
  geom_bar(stat = "identity", aes(fill = contact))+ 
  theme_bw()+ coord_flip() + 
  xlab("Different contact") + ylab("Numbers of Subscriptions") + ggtitle("Contact v.s. Subscription")
```


```{r, include=FALSE}
#####day vs subscription
data_day = subscribe %>%
  group_by(day) %>%
  summarise(n = n())
```
```{r, echo = FALSE}
#balance v.s. Subscription
ggplot(data=data_day, aes(x=day, y=n))+
  geom_bar(stat = "identity", aes(fill = day))+ 
  theme_bw()+ coord_flip() + 
  xlab("Day") + ylab("Numbers of Subscriptions") + ggtitle("Day v.s. Subscription")
```



```{r, include=FALSE}
#####month vs subscription
data_month = subscribe %>%
  group_by(month) %>%
  summarise(n = n())
```
```{r, echo = FALSE}
#month v.s. Subscription
ggplot(data=data_month, aes(x=month, y=n))+
  geom_bar(stat = "identity", aes(fill = month))+ 
  theme_bw()+ coord_flip() + 
  xlab("Different Month") + ylab("Numbers of Subscriptions") + ggtitle("Month v.s. Subscription")
```



```{r, include=FALSE}
#####duration vs subscription
data_duration = subscribe %>%
  group_by(duration) %>%
  summarise(n = n())
```
```{r, echo = FALSE}
#duration v.s. Subscription
ggplot(data=data_duration, aes(x=duration, y=n))+
  geom_bar(stat = "identity", aes(fill = duration))+ 
  theme_bw()+ coord_flip() + 
  xlab("Different duration") + ylab("Numbers of Subscriptions") + ggtitle("Duration v.s. Subscription")
```



```{r, include=FALSE}
#####campaign vs subscription
data_campaign = subscribe %>%
  group_by(campaign) %>%
  summarise(n = n())
```
```{r, echo = FALSE}
#campaign v.s. Subscription
ggplot(data=data_campaign, aes(x=campaign, y=n))+
  geom_bar(stat = "identity", aes(fill = campaign))+ 
  theme_bw()+ coord_flip() + 
  xlab("Numbers of Campaign") + ylab("Numbers of Subscriptions") + ggtitle("Campaign v.s. Subscription")
```



```{r, include=FALSE}
#####pdays vs subscription
data_pdays = subscribe %>%
  group_by(pdays) %>%
  summarise(n = n())
```
```{r, echo = FALSE}
#pdays v.s. Subscription
ggplot(data=data_pdays, aes(x=pdays, y=n))+
  geom_bar(stat = "identity", aes(fill = pdays))+ 
  theme_bw()+ coord_flip() + 
  xlab("Pdays") + ylab("Numbers of Subscriptions") + ggtitle("Pdays v.s. Subscription")
```



```{r, include=FALSE}
#####previous vs subscription
data_previous = subscribe %>%
  group_by(previous) %>%
  summarise(n = n())
```
```{r, echo = FALSE}
#previous v.s. Subscription
ggplot(data=data_previous, aes(x=previous, y=n))+
  geom_bar(stat = "identity", aes(fill = previous))+ 
  theme_bw()+ coord_flip() + 
  xlab("Previous") + ylab("Numbers of Subscriptions") + ggtitle("Previous v.s. Subscription")
```



```{r, include=FALSE}
#####poutcome vs subscription
data_poutcome = subscribe %>%
  group_by(poutcome) %>%
  summarise(n = n())
```
```{r, echo = FALSE}
#poutcome v.s. Subscription
ggplot(data=data_poutcome, aes(x=poutcome, y=n))+
  geom_bar(stat = "identity", aes(fill = poutcome))+ 
  theme_bw()+ coord_flip() + 
  xlab("Different Poutcome") + ylab("Numbers of Subscriptions") + ggtitle("Poutcome v.s. Subscription")
```


